server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: cloud-employee-management
  datasource:
    url: jdbc:mysql://lab06nguyenduyduc.crg64ymas1co.ap-southeast-1.rds.amazonaws.com:3306/lab6db?useSSL=true&allowPublicKeyRetrieval=true&serverTimezone=Asia/Ho_Chi_Minh
    username: nguyenduyduc
    password: Nguyenduyduc2671
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Ho_Chi_Minh

flyway:
  enabled: true
  locations: classpath:db/migration

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true

security:
  jwt:
    secret: ${JWT_SECRET:change-me}
    expiration: ${JWT_EXPIRATION_SECONDS:3600}


